export const SET_EXCHANGE_RATES_FAILED = "exchangeRates/SET_EXCHANGE_RATES_FAILED"
export const SET_EXCHANGE_RATES_ATTEMPT = "exchangeRates/SET_EXCHANGE_RATES_ATTEMPT"
export const SET_EXCHANGE_RATES_SUCCESS = "exchangeRates/SET_EXCHANGE_RATES_SUCCESS"
